/**
 * Warmup identity: how a warmup message is recognised, and the ONE predicate
 * every read surface (REST, MCP, IMAP, webhooks, stats, correlation) calls.
 *
 * Three markers, checked in order of certainty:
 *   1. Registry — the RFC822 Message-ID was generated by us and is in
 *      warmup_messages. Exact and cheap; both ends of every conversation are
 *      pool mailboxes, so we know every id in advance.
 *   2. Signed header — `X-OEM-Warmup: v1; <hmac>` bound to the Message-ID.
 *      Survives a provider rewriting the id (the hmac is over the id we sent,
 *      so a rewritten id fails; the header alone then still identifies the
 *      message as ours because only the master key can mint it).
 *   3. Body tag — the org's filter tag as the last line of the body, like
 *      Instantly's custom warmup tag. Works from listing metadata (subject or
 *      snippet) and lets external tools filter too.
 */

import crypto from 'node:crypto';
import { customAlphabet } from 'nanoid';
import { eq, inArray, sql } from 'drizzle-orm';
import { db, schema } from '../db/index.js';
import { config } from '../config.js';
import { normalizeMessageId } from '../inbound/classify.js';
import type { WarmupMessage } from '../db/schema.js';
import type { MessageSummary } from '../providers/types.js';

export const WARMUP_HEADER = 'X-OEM-Warmup';
const HEADER_VERSION = 'v1';

// No 0/O/1/I so the tag is unambiguous when read aloud or retyped.
const tagAlphabet = customAlphabet('23456789ABCDEFGHJKLMNPQRSTUVWXYZ', 7);
// Message-IDs mimic what each provider's own clients produce, so a warmup
// message is not recognisable by its id shape. The registry stores the
// normalised (lowercased) form; lookups normalise too.
const gmailAlphabet = customAlphabet('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-', 52);
const hexAlphabet = customAlphabet('0123456789abcdef', 32);

export function generateFilterTag(): string {
  return tagAlphabet();
}

/** A Message-ID in the sending provider's house style, plus its normalised form. */
export function newWarmupMessageId(senderEmail: string, provider: string = 'google'): { header: string; normalized: string } {
  const domain = (senderEmail.split('@')[1] ?? 'localhost').toLowerCase();
  let id: string;
  if (provider === 'google') {
    // Gmail and Workspace clients: "CA" + 52 base64url chars @mail.gmail.com
    id = `CA${gmailAlphabet()}@mail.gmail.com`;
  } else {
    // Outlook desktop / many clients: a UUID-shaped local part at the domain
    const h = hexAlphabet();
    id = `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-${h.slice(16, 20)}-${h.slice(20, 32)}@${domain}`;
  }
  return { header: `<${id}>`, normalized: id.toLowerCase() };
}

function hmacFor(normalizedId: string): string {
  return crypto
    .createHmac('sha256', config.masterKey)
    .update(`warmup:${normalizedId}`)
    .digest('base64url')
    .slice(0, 32);
}

export function warmupHeaderValue(normalizedId: string): string {
  return `${HEADER_VERSION}; ${hmacFor(normalizedId)}`;
}

/** True when the header was minted by this instance for this id (or, when
 *  the id was rewritten in transit, when the hmac matches any id we know). */
export function verifyWarmupHeader(value: string | null | undefined, normalizedId: string | null): boolean {
  if (!value) return false;
  const m = /^\s*v1\s*;\s*([A-Za-z0-9_-]{32})\s*$/.exec(value);
  if (!m) return false;
  const mac = m[1]!;
  if (normalizedId) {
    const expected = hmacFor(normalizedId);
    if (mac.length === expected.length && crypto.timingSafeEqual(Buffer.from(mac), Buffer.from(expected))) {
      return true;
    }
  }
  // Rewritten id: fall back to a registry scan of recent messages. Bounded
  // to the arrival window so it stays cheap.
  const since = Date.now() - 3 * 24 * 3600_000;
  const recent = db
    .select({ rfcMessageId: schema.warmupMessages.rfcMessageId })
    .from(schema.warmupMessages)
    .where(sql`${schema.warmupMessages.createdAt} > ${since}`)
    .all();
  return recent.some((r) => hmacFor(r.rfcMessageId) === mac);
}

// --- filter tags -------------------------------------------------------------

interface TagCache {
  tags: string[];
  refreshedAt: number;
}
let tagCache: TagCache = { tags: [], refreshedAt: 0 };
const TAG_CACHE_MS = 60_000;

/** Every tag that currently identifies warmup mail on this instance: each
 *  org's live tag plus recently replaced ones. The pool is instance-wide, so
 *  a mailbox receives mail carrying other orgs' tags. */
export function activeTags(): string[] {
  if (Date.now() - tagCache.refreshedAt < TAG_CACHE_MS) return tagCache.tags;
  const rows = db
    .select({
      tag: schema.orgs.warmupFilterTag,
      old: schema.orgs.warmupOldTagsJson,
    })
    .from(schema.orgs)
    .all();
  const tags = new Set<string>();
  const now = Date.now();
  for (const row of rows) {
    if (row.tag) tags.add(row.tag);
    if (row.old) {
      try {
        for (const o of JSON.parse(row.old) as { tag: string; until: number }[]) {
          if (o.until > now && o.tag) tags.add(o.tag);
        }
      } catch {
        // ignore a malformed row
      }
    }
  }
  tagCache = { tags: [...tags], refreshedAt: now };
  return tagCache.tags;
}

export function invalidateTagCache(): void {
  tagCache = { tags: [], refreshedAt: 0 };
}

/** The tag to stamp into outgoing mail: the org's tag only when the org
 *  switched the visible tag on; null otherwise (registry-only identification). */
export function orgTagIfEnabled(orgId: string): string | null {
  const org = db
    .select({ tag: schema.orgs.warmupFilterTag, enabled: schema.orgs.warmupTagEnabled })
    .from(schema.orgs)
    .where(eq(schema.orgs.id, orgId))
    .get();
  if (!org?.enabled) return null;
  return org.tag ?? ensureOrgTag(orgId);
}

/** The org's tag, generated on first use. */
export function ensureOrgTag(orgId: string): string {
  const org = db
    .select({ tag: schema.orgs.warmupFilterTag })
    .from(schema.orgs)
    .where(eq(schema.orgs.id, orgId))
    .get();
  if (org?.tag) return org.tag;
  const tag = generateFilterTag();
  db.update(schema.orgs).set({ warmupFilterTag: tag }).where(eq(schema.orgs.id, orgId)).run();
  invalidateTagCache();
  return tag;
}

/** Replace the org's tag; the old one keeps matching for 30 days. */
export function setOrgTag(orgId: string, newTag: string): void {
  const clean = newTag.trim().toUpperCase().replace(/[^A-Z0-9]/g, '');
  if (clean.length < 5 || clean.length > 16) {
    throw new Error('Filter tag must be 5–16 letters or digits');
  }
  const org = db.select().from(schema.orgs).where(eq(schema.orgs.id, orgId)).get();
  if (!org) throw new Error('Unknown organization');
  let old: { tag: string; until: number }[] = [];
  try {
    old = org.warmupOldTagsJson ? (JSON.parse(org.warmupOldTagsJson) as typeof old) : [];
  } catch {
    old = [];
  }
  const now = Date.now();
  old = old.filter((o) => o.until > now);
  if (org.warmupFilterTag && org.warmupFilterTag !== clean) {
    old.push({ tag: org.warmupFilterTag, until: now + 30 * 24 * 3600_000 });
  }
  db.update(schema.orgs)
    .set({ warmupFilterTag: clean, warmupOldTagsJson: JSON.stringify(old.slice(-5)) })
    .where(eq(schema.orgs.id, orgId))
    .run();
  invalidateTagCache();
}

function containsTag(text: string | null | undefined, tags: string[]): boolean {
  if (!text || tags.length === 0) return false;
  return tags.some((t) => text.includes(t));
}

// --- the predicate ---------------------------------------------------------

export interface IdentityInput {
  /** Raw Message-ID header value, any format. */
  messageId?: string | null;
  /** Header accessor for the signed marker (parsed mail or raw). */
  header?: (name: string) => string | null;
  subject?: string | null;
  text?: string | null;
  snippet?: string | null;
}

export interface IdentityResult {
  warmup: boolean;
  via: 'registry' | 'header' | 'tag' | null;
  /** The registry row, when identified through it. */
  message?: WarmupMessage;
}

export function lookupRegistry(messageId: string | null | undefined): WarmupMessage | undefined {
  const normalized = normalizeMessageId(messageId);
  if (!normalized) return undefined;
  return db
    .select()
    .from(schema.warmupMessages)
    .where(eq(schema.warmupMessages.rfcMessageId, normalized))
    .get();
}

export function isWarmupMessage(input: IdentityInput): IdentityResult {
  const normalized = normalizeMessageId(input.messageId);
  if (normalized) {
    const row = db
      .select()
      .from(schema.warmupMessages)
      .where(eq(schema.warmupMessages.rfcMessageId, normalized))
      .get();
    if (row) return { warmup: true, via: 'registry', message: row };
  }
  if (input.header) {
    const value = input.header(WARMUP_HEADER);
    if (value && verifyWarmupHeader(value, normalized)) return { warmup: true, via: 'header' };
  }
  const tags = activeTags();
  if (
    containsTag(input.subject, tags) ||
    containsTag(input.snippet, tags) ||
    containsTag(input.text, tags)
  ) {
    return { warmup: true, via: 'tag' };
  }
  return { warmup: false, via: null };
}

/** Drop warmup messages from a listing. Uses one batched registry lookup on
 *  Message-ID plus the tag check on subject/snippet. */
export function filterSummaries(summaries: MessageSummary[]): MessageSummary[] {
  if (summaries.length === 0) return summaries;
  const ids = summaries
    .map((s) => normalizeMessageId(s.messageId))
    .filter((v): v is string => !!v);
  const known = new Set<string>();
  if (ids.length > 0) {
    const rows = db
      .select({ id: schema.warmupMessages.rfcMessageId })
      .from(schema.warmupMessages)
      .where(inArray(schema.warmupMessages.rfcMessageId, ids))
      .all();
    for (const r of rows) known.add(r.id);
  }
  const tags = activeTags();
  return summaries.filter((s) => {
    const n = normalizeMessageId(s.messageId);
    if (n && known.has(n)) return false;
    if (containsTag(s.subject, tags) || containsTag(s.snippet, tags)) return false;
    return true;
  });
}
